# Generated by Django 5.0.1 on 2024-01-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolApp', '0001_initialTables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('semester', models.IntegerField(db_column='Semestr')),
                ('legitimate', models.IntegerField(blank=True, db_column='Usprawiedliwione', null=True)),
                ('illegitimate', models.IntegerField(blank=True, db_column='Nieusprawiedliwione', null=True)),
                ('lateAttendance', models.IntegerField(blank=True, db_column='Spoznienia', null=True)),
                ('present', models.IntegerField(blank=True, db_column='Obecny', null=True)),
            ],
            options={
                'db_table': 'Frekwencja',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Frequency',
        ),
    ]
